import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    dashboard: 'Dashboard',
    residents: 'Residents',
    payments: 'Payments',
    bank: 'Bank',
    reminders: 'Reminders',
    reports: 'Reports',
    settings: 'Settings',
    paymentReminders: 'Payment Reminders',
    financialReports: 'Financial Reports',
    manageSystem: 'Manage system configuration',
    houses: 'Houses',
    users: 'Users',
    integrations: 'Integrations',
    // Global Actions
    export: 'Export',
    send: 'Send',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    addUnit: 'Add Unit',
    addUser: 'Add User',
    addResident: 'Add Resident',
    addPayment: 'Add Payment',
    confirm: 'Confirm',
    cancel: 'Cancel',
    // Stats Cards
    totalCharged: 'Total Charged',
    totalReceived: 'Total Received',
    outstandingBalance: 'Outstanding Balance',
    overdueResidents: 'Overdue Residents',
    occupancy: 'Occupancy Rate',
    healthy: 'Healthy collection rate',
    needsSupport: 'Needs collection support',
    // Statuses
    overdue: 'Overdue',
    partial: 'Partial',
    matched: 'Matched',
    unmatched: 'Unmatched',
    active: 'Active',
    inactive: 'Inactive',
    // Table Headers
    resident: 'Resident',
    house: 'House',
    amount: 'Amount',
    status: 'Status',
    actions: 'Actions',
    charged: 'Charged',
    paid: 'Paid',
    outstanding: 'Outstanding',
    details: 'Details',
    date: 'Date',
    description: 'Description',
    // Section sub-headers & templates
    incomeVsOutstanding: 'Income vs Outstanding',
    revenueOverview: 'Revenue Overview',
    ledgerSummary: 'Ledger Summary',
    exportOptions: 'Export Options',
    variables: 'Variables',
    noticeBody: 'Notice Body Template',
    activity: 'Activity',
    viewAll: 'View All',
    allHouses: 'All Houses',
    allStatuses: 'All Statuses',
    monthlyCharge: 'Monthly Charge',
    searchPlaceholder: 'Search by resident name...',
    paid: 'Paid',
    paymentsHistory: 'Payments History',
    recordPayment: 'Record Payment',
    searchPaymentsPlaceholder: 'Search by resident or ID...',
    thisMonth: 'This Month',
    moreFilters: 'More Filters',
    completed: 'Completed',
    pending: 'Pending',
    idDate: 'ID / Date',
    method: 'Method',
    appliedOutstanding: 'Applied to outstanding',
    reconciliationStatus: 'Reconciliation Status',
    allAllocated: 'All payments are fully allocated',
    bankTransactions: 'Bank Transactions',
    connectBank: 'Connect Bank',
    searchBankPlaceholder: 'Search by description...',
    matchAction: 'Match Action',
    confirmMatch: 'Confirm Match',
    upload: 'Upload',
    findResidentPlaceholder: 'Find resident...',
    all: 'All',
    allCaughtUp: 'All caught up!',
    audience: 'Audience',
    channel: 'Channel',
    sendBatch: 'Send batch',
    message: 'Message',
    housesConfiguration: 'Houses Configuration',
    reminderNoticeEditor: 'Reminder Notice Editor',
    saveDefaults: 'Save Defaults',
    availableIntegrations: 'Available Integrations',
    occupied: 'Occupied',
    vacant: 'Vacant',
    manage: 'Manage',
    connect: 'Connect',
  },
  de: {
    dashboard: 'Dashboard',
    residents: 'Bewohner',
    payments: 'Zahlungen',
    bank: 'Bank',
    reminders: 'Erinnerungen',
    reports: 'Berichte',
    settings: 'Einstellungen',
    paymentReminders: 'Zahlungserinnerungen',
    financialReports: 'Berichte',
    manageSystem: 'Systemkonfiguration verwalten',
    houses: 'Häuser',
    users: 'Benutzer',
    integrations: 'Integrationen',
    // Global Actions
    export: 'Exportieren',
    send: 'Senden',
    save: 'Speichern',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    addUnit: 'Einheit hinzufügen',
    addUser: 'Benutzer hinzufügen',
    addResident: 'Bewohner hinzufügen',
    addPayment: 'Zahlung hinzufügen',
    confirm: 'Bestätigen',
    cancel: 'Abbrechen',
    // Stats Cards
    totalCharged: 'Gesamt berechnet',
    totalReceived: 'Gesamt erhalten',
    outstandingBalance: 'Offener Betrag',
    overdueResidents: 'Überfällige Bewohner',
    occupancy: 'Belegungsrate',
    healthy: 'Gesunde Inkassoquote',
    needsSupport: 'Benötigt Inkassounterstützung',
    // Statuses
    overdue: 'Überfällig',
    partial: 'Teilweise',
    matched: 'Abgeglichen',
    unmatched: 'Nicht abgeglichen',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    // Table Headers
    resident: 'Bewohner',
    house: 'Haus',
    amount: 'Betrag',
    status: 'Status',
    actions: 'Aktionen',
    charged: 'Berechnet',
    paid: 'Bezahlt',
    outstanding: 'Offen',
    details: 'Details',
    date: 'Datum',
    description: 'Beschreibung',
    // Section sub-headers & templates
    incomeVsOutstanding: 'Einnahmen vs. Offen',
    revenueOverview: 'Umsatzübersicht',
    ledgerSummary: 'Hauptbuch-Zusammenfassung',
    exportOptions: 'Export-Optionen',
    variables: 'Variablen',
    noticeBody: 'Nachrichtenvorlage',
    activity: 'Aktivität',
    viewAll: 'Alle ansehen',
    allHouses: 'Alle Häuser',
    allStatuses: 'Alle Status',
    monthlyCharge: 'Monatliche Gebühr',
    searchPlaceholder: 'Nach Bewohnernamen suchen...',
    paid: 'Bezahlt',
    paymentsHistory: 'Zahlungsverlauf',
    recordPayment: 'Zahlung aufzeichnen',
    searchPaymentsPlaceholder: 'Suche nach Bewohner oder ID...',
    thisMonth: 'Diesen Monat',
    moreFilters: 'Mehr Filter',
    completed: 'Abgeschlossen',
    pending: 'Ausstehend',
    idDate: 'ID / Datum',
    method: 'Methode',
    appliedOutstanding: 'Auf offene Posten angerechnet',
    reconciliationStatus: 'Abgleichstatus',
    allAllocated: 'Alle Zahlungen sind vollständig zugeordnet',
    bankTransactions: 'Banktransaktionen',
    connectBank: 'Bank verbinden',
    searchBankPlaceholder: 'Suche nach Beschreibung...',
    matchAction: 'Abgleich-Aktion',
    confirmMatch: 'Abgleich bestätigen',
    upload: 'Hochladen',
    findResidentPlaceholder: 'Bewohner finden...',
    all: 'Alle',
    allCaughtUp: 'Alles erledigt!',
    audience: 'Empfänger',
    channel: 'Kanal',
    sendBatch: 'Stapel senden',
    message: 'Nachricht',
    housesConfiguration: 'Häuser-Konfiguration',
    reminderNoticeEditor: 'Erinnerungsschreiben-Editor',
    saveDefaults: 'Standardwerte speichern',
    availableIntegrations: 'Verfügbare Integrationen',
    occupied: 'Belegt',
    vacant: 'Vakant',
    manage: 'Verwalten',
    connect: 'Verbinden',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');
  
  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
